
name: Trigger Repository Update

on:
  push:
    branches:
      - lazy.nvim

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: etherbiswas/dotfiles
          event-type: update-subtree
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
