
name: Update Repository

on:
  repository_dispatch:
    types: [update-subtree]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Repository
        run: |
          git subtree pull --prefix=.config/nvim https://github.com/etherbiswas/nvim.git hyprland --squash

      - name: Push changes
        run: |
          git push
