name: Push Dotfiles Neovim Changes to Nvim Repo

on:
  push:
    branches:
      - hyprland  # Change to match your `dotfiles` branch

jobs:
  push-to-nvim:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dotfiles repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  #  This is the fix!
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Check for changes in Neovim config
        id: check_changes
        run: |
          cd .config/nvim
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected in Neovim config."
            echo "push_needed=true" >> $GITHUB_ENV
          else
            echo "No changes detected."
            echo "push_needed=false" >> $GITHUB_ENV
          fi

      - name: Push changes to Neovim repo
        if: env.push_needed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  #  Fixing missing token
        run: |
          cd .config/nvim
          git add .
          git commit -m "Auto-sync: Changes from dotfiles repo"
          git push https://etherbiswas:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/etherbiswas/nvim.git lazy.nvim  # 🔥 Using token for authentication
