# dotfiles Workflow (Update Nvim Subtree) - Best Version

name: Update Nvim Subtree

on:
  repository_dispatch:
    types: [update-subtree]
  workflow_dispatch:

jobs:
  update-subtree:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes

    steps:
      - name: Checkout dotfiles repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: hyprland
          fetch-depth: 0

      - name: Set Git author identity
        run: |
          git config --global user.name "Ether Biswas"
          git config --global user.email "etherrorcode404@gmail.com"

      - name: Pull latest nvim updates into dotfiles repo
        run: |
          git subtree pull --prefix=.config/nvim https://github.com/etherbiswas/nvim.git lazy.nvim --squash || echo "No updates to pull"

      - name: Get latest nvim commit message
        id: commit_msg
        run: |
          cd .config/nvim
          latest_commit_msg=$(git log -1 --pretty=%B)
          echo "latest_commit_msg=$latest_commit_msg" >> $GITHUB_ENV

      - name: Commit and push updated Neovim config to dotfiles
        run: |
          git add .config/nvim
          git commit -m "${{ env.latest_commit_msg }}" || echo "No changes to commit"
          git push origin hyprland
